[package]
name = "wc-rs"
version = "0.1.0"
authors = ["Jesse Mazzella <jessemazzella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "wc-rs"
path = "src/bin/wc.rs"